insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'An Bình', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'An Dương Vương', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'An Phú Đông 27', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'An Sơn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'An Tôn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Bà Huyện Thanh Quan', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Bà Triệu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Bạch Đằng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Bế Văn Đàn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Bình An', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Bùi Thị Xuân', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Cách Mạng Tháng Tám', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Cam Ly', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Cao Bá Quát', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Cao Thắng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Châu Văn Liêm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Chi Lăng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Chu Văn An', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Cô Bắc', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Cô Giang', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Cổ Loa', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Công Chúa Ngọc Hân', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Cù Chính Lan', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Cúc Quỳ', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'ĐT 725', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đa Minh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đa Phú', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đa Quý', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đa Sa', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đa Thiện', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Dã Tượng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đặng Thái Thân', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đào Duy Từ', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đất Làng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đinh Công Tráng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đinh Tiên Hoàng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đoàn Thị Điểm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đồi Công Đoàn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đồi Đông Tĩnh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đồi Huy Hoàng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đồi Phật Bà', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đồi Thông Tin', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đống Đa', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đông Hưng Thuận 6', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đồng Tâm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đông Tĩnh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường 2/3', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường 20', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường 3/2', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường 3/4', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường 47', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường 50', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường 66', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường 725', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường Ankroet', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường B24', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường Đankia', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường Mimosa', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường Pasteur', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường T21', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường Yagout', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Đường Yersin', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Gio An', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hà Huy Tập', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hai Bà Trưng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hải Thượng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hàn Giang', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hàn Thuyên', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hậu Lân', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hiệp Thành 13', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hồ Than Thở', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hồ Tùng Mậu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hồ Xuân Hương', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hoa Hồng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hoa Phượng Tím', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hoàng Diệu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hoàng Hoa Thám', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hoàng Văn Thụ', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Hùng Vương', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Huyền Trân Công Chúa', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Huỳnh Tấn Phát', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Huỳnh Thúc Kháng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Khe Sanh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Khởi Nghĩa Bắc Sơn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Kim Đồng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Kim Thạch', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'La Sơn Phu Tử', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lâm Văn Thạnh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lãnh Địa Đức Bà', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lê Đại Hành', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lê Hồng Phong', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lê Lai', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lê Quý Đôn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lê Thánh Tôn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lê Thị Hồng Gấm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lê Thị Riêng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lê Văn Hoàn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lê Văn Tâm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lê Văn Tám', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lộ Đức', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lộc Hòa', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lộc Quý', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lữ Gia', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lương Đình Của', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lương Thế Vinh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lý Nam Đế', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lý Ông Trọng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lý Thường Kiệt', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Lý Tự Trọng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Ma Trang Sơn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Mạc Đĩnh Chi', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Mai Anh Đào', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Mai Hắc Đế', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Mai Hoa Thôn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Mai Xuân Thưởng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Măng Lin', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Măng Ling', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Mẫu Tâm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Mê Linh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Mương Khai', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nam Hồ', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nam Kỳ Khởi Nghĩa', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Ngô Gia Tự', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Ngô Huy Diễn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Ngô Quyền', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Ngô Tất Tố', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Ngô Thì Nhậm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Ngô Thì Sỹ', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Ngô Văn Sở', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn An Ninh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Biểu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Chí Thanh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Công Trứ', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Đình Chiểu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Đình Quân', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Du', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Hoàng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Hữu Cảnh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Hữu Cầu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Huy Chương', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Khanh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Khuyến', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Lương Bằng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyên Phi Ỷ Lan', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Siêu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Thái Bình', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Thái Học', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Thị Định', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Thị Minh Khai', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Thị Nghĩa', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Thị Thử', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Thượng Hiền', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Trãi', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Trung Trực', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyên Tử Lực', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Văn Cừ', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Văn Trỗi', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nguyễn Viết Xuân', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Nhà Chung', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Núi Một', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phạm Hồng Thái', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phạm Ngọc Thạch', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phạm Ngũ Lão', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phan Bội Châu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phan Chu Trinh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phan Đình Giót', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phan Đình Phùng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phan Như Thạch', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phê Thạch', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phó Đức Chính', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phù Đổng Thiên Vương', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phú Trung', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Phước Thành', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Quảng Thắng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Quang Trung', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Quốc Lộ 20', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Sư Vạn Hạnh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Sương Nguyệt Ánh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tà Nung', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tân Chánh Hiệp 16', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tân Chánh Hiệp 2', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tân Thới Hiệp 10', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tăng Bạt Hổ', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thái Lâm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thái Phiên', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thạnh Lộc 27', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thánh Mẫu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thanh Tâm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thánh Tâm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thạnh Xuân 13', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thạnh Xuân 21', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thi Sách', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thích Bửu Đăng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thiện Mỹ', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thiên Thành', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thiện Ý', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thông Thiên Học', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Thủ Khoa Huân', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tỉnh lộ 722', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tỉnh lộ 723', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tỉnh lộ 725', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tô Hiến Thành', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tô Hiệu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tô Ngọc Vân', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tô Vĩnh Diện', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tôn Thất Tùng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trại Gà', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trại Mát', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Anh Tông', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Bình Trọng', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Đại Nghĩa', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Hưng Đạo', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Khánh Dư', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Lê', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Nhân Tông', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Nhật Duật', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Phú', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Quang Đạo', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Quang Diệu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Quang Khải', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Quốc Toản', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Quý Cáp', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Thái Tông', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Thánh Tông', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Thị Bạch Liên', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trần Văn Côi', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trạng Trình', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trích Sài', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Triệu Việt Vương', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trịnh Hoài Đức', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trường Chinh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trương Công Định', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trương Văn Đa', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Trương Văn Hoàn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tự Phước', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tùng Lâm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tương Phố', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Tuyền Lâm', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Vạn Hạnh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Vạn Kiếp', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Vạn Thành', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Võ Thị Sáu', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Võ Trường Toản', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Vòng Lâm Viên', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Xa La', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Xô Viết Nghệ Tĩnh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Xuân An', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Xuân Sơn', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Xuân Thọ', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Y Dinh', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Yên Thế', '0', '0', now(), now());
insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) values ('123', 'Yết Kiêu', '0', '0', now(), now());

Insert into locations_streets (code, street_name, district_code, ward_code, created_at, updated_at) VALUES ('123', 'Street A', '0', '0', NOW(), NOW());
